### ISSUE TITLE
4-02 talk example issue

### ISSUE THREAD

**Issue by Tombodil** [IITIDIDX597/4-02-Talk-Example#2]
wanting to make an issue and then show it's relationship to zenhub

**Comment by Tombodil** [comment]
I'm leaving a comment and this issue should be reopened!

**Comment by lannesnunes** [comment]
cool! @Tombodil

**Comment by Tombodil** [comment]
> I'm leaving a comment and this issue should be reopened!

quoted from earlier

**Comment by Tombodil** [comment]
> cool! @Tombodil
left from someone else!
